m4_include([config/general.m4])
m4_include([config/perl.m4])
m4_include([config/libtool.m4])
m4_include([config/compiler.m4])
m4_include([config/libc.m4])
m4_include([config/acx_pthread.m4])
m4_include([config/acx_libpq.m4])
m4_include([config/acx_slonytools.m4])
m4_include([config/docbook.m4])
m4_include([config/docs.m4])

