subscribe set (id=1, provider=1, receiver = 2, forward=yes);
wait for event (origin=all, confirmed=all, wait on=1);
subscribe set (id=2, provider=1, receiver = 2, forward=yes);
wait for event (origin=all, confirmed=all, wait on=1);
subscribe set (id=3, provider=1, receiver = 2, forward=yes);
wait for event (origin=all, confirmed=all, wait on=1);
subscribe set (id=4, provider=1, receiver = 2, forward=yes);
wait for event (origin=all, confirmed=all, wait on=1);
subscribe set (id=5, provider=1, receiver = 2, forward=yes);
wait for event (origin=all, confirmed=all, wait on=1);
subscribe set (id=6, provider=1, receiver = 2, forward=yes);
wait for event (origin=all, confirmed=all, wait on=1);
subscribe set (id=7, provider=1, receiver = 2, forward=yes);
wait for event (origin=all, confirmed=all, wait on=1);
subscribe set (id=8, provider=1, receiver = 2, forward=yes);
wait for event (origin=all, confirmed=all, wait on=1);
subscribe set (id=9, provider=1, receiver = 2, forward=yes);
wait for event (origin=all, confirmed=all, wait on=1);
subscribe set (id=10, provider=1, receiver = 2, forward=yes);
wait for event (origin=all, confirmed=all, wait on=1);


subscribe set (id=1, provider=2, receiver = 3, forward=yes);
wait for event (origin=all, confirmed=all, wait on=1);
subscribe set (id=2, provider=2, receiver = 3, forward=yes);
wait for event (origin=all, confirmed=all, wait on=1);
subscribe set (id=3, provider=2, receiver = 3, forward=yes);
wait for event (origin=all, confirmed=all, wait on=1);
subscribe set (id=4, provider=2, receiver = 3, forward=yes);
wait for event (origin=all, confirmed=all, wait on=1);
subscribe set (id=5, provider=2, receiver = 3, forward=yes);
wait for event (origin=all, confirmed=all, wait on=1);
subscribe set (id=6, provider=2, receiver = 3, forward=yes);
wait for event (origin=all, confirmed=all, wait on=1);
subscribe set (id=7, provider=2, receiver = 3, forward=yes);
wait for event (origin=all, confirmed=all, wait on=1);
subscribe set (id=8, provider=2, receiver = 3, forward=yes);
wait for event (origin=all, confirmed=all, wait on=1);
subscribe set (id=9, provider=2, receiver = 3, forward=yes);
wait for event (origin=all, confirmed=all, wait on=1);
subscribe set (id=10, provider=2, receiver = 3, forward=yes);
wait for event (origin=all, confirmed=all, wait on=1);
