lock set (id=1, origin=1);
move set (id=1, old origin=1, new origin=3);
lock set (id=2, origin=1);
move set (id=2, old origin=1, new origin=3);
lock set (id=3, origin=1);
move set (id=3, old origin=1, new origin=3);
lock set (id=4, origin=1);
move set (id=4, old origin=1, new origin=3);
lock set (id=5, origin=1);
move set (id=5, old origin=1, new origin=3);
lock set (id=6, origin=1);
move set (id=6, old origin=1, new origin=3);
lock set (id=7, origin=1);
move set (id=7, old origin=1, new origin=3);
lock set (id=8, origin=1);
move set (id=8, old origin=1, new origin=3);
lock set (id=9, origin=1);
move set (id=9, old origin=1, new origin=3);
lock set (id=10, origin=1);
move set (id=10, old origin=1, new origin=3);