# $Id: Makefile.backend,v 1.1 2005-03-11 20:09:47 cbbrowne Exp $

MODULES=slony1_funcs
slony_subdir = src/slony1_funcs
slony_top_builddir = ../..
include $(slony_top_builddir)/Makefile.global
CFLAGS += -I$(slony_top_builddir)

ifdef USE_PGXS
PGXS = $(shell pg_config --pgxs)
include $(PGXS)
else
top_builddir = $(PGSOURCETREE)
include $(PGSOURCETREE)/contrib/contrib-global.mk
endif
