AROPT = crs
AWK= awk
 
DLSUFFIX = .so
CFLAGS_SL =
BE_DLLLIBS= -bundle_loader $(pgbindir)/postgres
 
# Rule for building shared libs (currently used only for regression test
# shlib ... should go away, since this is not really enough knowledge)
%.so: $(SO_OBJS)
	$(CC) -bundle -o $@ $< $(BE_DLLLIBS)

sqlmansect = 7
