MK_NO_LORDER= true
AR= ar
AROPT = cr
LD= $(AR)
LDREL= $(AROPT)
LDOUT=
LDFLAGS=

enable_shared = no
DLSUFFIX = .so
CFLAGS_SL =

%$(DLSUFFIX): $(SO_OBJS)
	@echo 'cannot make shared object $@ from $<'

sqlmansect = 7
