# Makefile for src
# Author: Jan Wieck, Afilias USA INC.
#
#	$Header: /local/home/ssinger/cvs2svn/cvs2svn-2.3.0/slony-cvsd/slony1-engine/src/Makefile,v 1.1 2003-11-17 17:29:00 wieck Exp $
#

subdir = src
top_builddir = ..
include $(top_builddir)/Makefile.global

all install installdirs clean distclean maintainer-clean:
	$(MAKE) -C xxid $@
