# ----------
# Makefile for src
#
#	Copyright (c) 2003, PostgreSQL Global Development Group
#	Author: Jan Wieck, Afilias USA INC.
#
#	$Id: Makefile,v 1.2 2003-11-18 15:11:35 wieck Exp $
# ----------

subdir = src
top_builddir = ..
include $(top_builddir)/Makefile.global

all install installdirs clean distclean maintainer-clean:
	$(MAKE) -C xxid $@
